"""add webhook targets

Revision ID: 14ee1c19565f
Revises: fa74134220e9
Create Date: 2026-06-21 20:49:10.497401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ee1c19565f'
down_revision: Union[str, Sequence[str], None] = 'fa74134220e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_targets')
    # ### end Alembic commands ###
