"""add player accounts and profile fields

Revision ID: a4b7f7e9f223
Revises: 14ee1c19565f
Create Date: 2026-06-23 06:27:15.948169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b7f7e9f223'
down_revision: Union[str, Sequence[str], None] = '14ee1c19565f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('players', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('avatar_path', sa.String(), nullable=True))
    op.add_column('players', sa.Column('flight_image_path', sa.String(), nullable=True))
    op.add_column('players', sa.Column('accent_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'accent_color')
    op.drop_column('players', 'flight_image_path')
    op.drop_column('players', 'avatar_path')
    op.drop_column('players', 'display_name')
    op.drop_column('players', 'password_hash')
    # ### end Alembic commands ###
